/*
 * Turns an audit run (npm run audit:ui) into something reviewable.
 *
 *   audit-shots/report.md       — every measured fact, one row per cell, and the
 *                                 cells that tripped a rule pulled to the top
 *   audit-shots/sheets/*.png    — contact sheets: one per surface per theme
 *                                 (data × width), and one for the network states
 *
 * Measured facts are leads, not verdicts: a red region may be a lit key that is
 * genuinely "now", a small target may be a chip inside a dense row. The written
 * findings in .agents/UI_AUDIT.md are what the shots were checked against.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { chromium } from '@playwright/test';

const ROOT = join(process.cwd(), 'audit-shots');
const facts = readdirSync(join(ROOT, 'facts'))
  .map((f) => JSON.parse(readFileSync(join(ROOT, 'facts', f), 'utf8')))
  .sort((a, b) => a.id.localeCompare(b.id));

const WIDTHS = ['w375', 'w768', 'w1280'];
const DATA = ['empty', 'typical', 'overflowing'];
const STATES = ['typical-loading', 'typical-error', 'typical-offline'];
const surfaces = [...new Set(facts.map((f) => f.surface))];

// ── report.md ────────────────────────────────────────────────────────────────
const flag = (f) => {
  const out = [];
  if (f.overflowX > 0) out.push(`scrolls sideways ${f.overflowX}px`);
  if (f.loadingWords.length) out.push(`"${f.loadingWords[0].trim()}"`);
  if (f.placeholderTimings) out.push(`${f.placeholderTimings}× "50 min"`);
  if (f.redRegions > 1) out.push(`${f.redRegions} red regions`);
  if (f.state === 'loaded' && f.skeletonMs === null) out.push('never settled');
  if (f.state === 'loaded' && f.skeletonMs > 1500) out.push(`settled in ${f.skeletonMs}ms`);
  if (f.errors.length) out.push(`${f.errors.length} console error(s)`);
  if (f.unlabelledIconButtons) out.push(`${f.unlabelledIconButtons} unlabelled icon button(s)`);
  return out;
};

const lines = [
  '# UI audit — measured facts',
  '',
  `${facts.length} cells. Generated by scripts/audit-report.mjs; findings are in .agents/UI_AUDIT.md.`,
  '',
  '## Cells that tripped a rule',
  '',
  '| Cell | Flags |',
  '|---|---|',
  ...facts.filter((f) => flag(f).length).map((f) => `| ${f.id} | ${flag(f).join(' · ')} |`),
  '',
  '## Small touch targets at 375px (loaded, dark, typical)',
  '',
  '| Surface | Count | Sample |',
  '|---|---|---|',
  ...facts
    .filter((f) => f.width === 375 && f.theme === 'dark' && f.state === 'loaded' && f.data === 'typical')
    .map((f) => `| ${f.surface} | ${f.smallTargets} | ${f.smallSample.slice(0, 4).join(', ').replace(/\|/g, '/')} |`),
  '',
  '## Red regions (dark, typical, 1280)',
  '',
  '| Surface | Count | Sample |',
  '|---|---|---|',
  ...facts
    .filter((f) => f.width === 1280 && f.theme === 'dark' && f.state === 'loaded' && f.data === 'typical')
    .map((f) => `| ${f.surface} | ${f.redRegions} | ${f.redSample.slice(0, 4).join(', ').replace(/\|/g, '/')} |`),
  '',
  '## Console errors',
  '',
  ...facts.filter((f) => f.errors.length).map((f) => `- **${f.id}** — ${f.errors.slice(0, 3).join(' / ')}`),
  '',
];
writeFileSync(join(ROOT, 'report.md'), lines.join('\n'));

// ── contact sheets ───────────────────────────────────────────────────────────
const shot = (id) => pathToFileURL(join(ROOT, 'shots', `${id}.png`)).href;
const has = new Set(facts.map((f) => f.id));

// Each tile shows the top of the page at a common height, scaled so the three
// widths sit side by side; what is below the fold is in the full shot.
const tile = (id, label) =>
  has.has(id)
    ? `<figure><figcaption>${label}</figcaption><div class="crop"><img src="${shot(id)}"></div></figure>`
    : `<figure><figcaption>${label}</figcaption><div class="crop missing">—</div></figure>`;

const page = (title, rows) => `<!doctype html><html><head><style>
  body { margin: 0; padding: 16px; background: #777; font: 12px/1.3 monospace; color: #000; }
  h1 { font-size: 16px; margin: 0 0 12px; }
  .row { display: flex; gap: 12px; margin-bottom: 14px; align-items: flex-start; }
  .rowlabel { width: 90px; font-weight: bold; padding-top: 18px; }
  figure { margin: 0; }
  figcaption { height: 16px; }
  .crop { width: 300px; height: 900px; overflow: hidden; background: #444; outline: 1px solid #000; }
  .crop img { width: 100%; display: block; }
  .missing { display: grid; place-items: center; color: #ddd; }
</style></head><body><h1>${title}</h1>${rows}</body></html>`;

mkdirSync(join(ROOT, 'sheets'), { recursive: true });
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1100, height: 800 } });
const tab = await ctx.newPage();

async function render(name, html) {
  const file = join(ROOT, 'sheets', `${name}.html`);
  writeFileSync(file, html);
  await tab.goto(pathToFileURL(file).href);
  await tab.waitForFunction(() => Array.from(document.images).every((i) => i.complete));
  await tab.screenshot({ path: join(ROOT, 'sheets', `${name}.png`), fullPage: true });
}

for (const s of surfaces) {
  for (const theme of ['dark', 'light']) {
    const rows = DATA.filter((d) => WIDTHS.some((w) => has.has(`${s}__${d}__${theme}__${w}`)))
      .map((d) => `<div class="row"><div class="rowlabel">${d}</div>${WIDTHS.map((w) => tile(`${s}__${d}__${theme}__${w}`, w)).join('')}</div>`)
      .join('');
    await render(`${s}-${theme}`, page(`${s} · ${theme}`, rows));
  }
  const stateRows = STATES.filter((st) => has.has(`${s}__${st}__dark__w375`))
    .map((st) => `<div class="row"><div class="rowlabel">${st.replace('typical-', '')}</div>${['w375', 'w1280'].map((w) => tile(`${s}__${st}__dark__${w}`, w)).join('')}</div>`)
    .join('');
  if (stateRows) await render(`${s}-states`, page(`${s} · network states (dark)`, stateRows));
}
await browser.close();
process.stdout.write(`${facts.length} cells → audit-shots/report.md and ${surfaces.length} surfaces of contact sheets\n`);
